server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Angular rutiranje
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. API pozivi
    location /api/ {
        proxy_pass http://unileague-backend:8080/api/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Logos
    location /logos/ {
        proxy_pass http://unileague-backend:8080/logos/;
        proxy_set_header Host $host;
    }

    # 4. Players
    location /players/ {
        proxy_pass http://unileague-backend:8080/players/;
        proxy_set_header Host $host;
    }

   
}